[package]
name = "mzpeak_prototyping"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mzpeak_prototyping"
path = "src/main.rs"

[[example]]
name = "convert"
path = "examples/convert.rs"

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "peak_mass_error_check"
path = "examples/peak_mass_error_check.rs"

[[example]]
name = "read_spectrum"
path = "examples/read_spectrum.rs"

[[example]]
name = "read"
path = "examples/read.rs"

[[example]]
name = "extract-ref"
path = "examples/extract_ref.rs"

[[example]]
name = "extract"
path = "examples/extract.rs"

[[example]]
name = "extract-object-store"
path = "examples/extract_object_store.rs"
required-features = ["async"]

[[example]]
name = "extract-ref-object-store"
path = "examples/extract_ref_object_store.rs"
required-features = ["async"]

[features]
default = ["async"]

async = ["dep:tokio", "dep:async_zip", "dep:object_store", "parquet/async", "dep:futures", "mzdata/async_partial", "dep:url"]
s3 = ["object_store/aws", "async"]

thermo = ["mzdata/thermo"]

[dependencies]
arrow = "55.2.0"
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.27"
mzdata = { version = "0.60.3", features = ["serde", "bruker_tdf", "nalgebra", "zstd", "numpress"] }
parquet = { version = "55.2.0" }
serde = { version = "1.0.219", features = ["derive"] }
mzpeaks = "1.0.9"
num-traits = "0.2.19"
serde_json = "1.0.140"
serde_with = "3.12.0"
zip = "4.1.0"
bytes = "1.10.1"
nalgebra = "0.33.2"
bytemuck = "1.23.1"

# For the benchmark CLI, to eventually be factored out if switching to workspace
clap = { version = "4.5.38", features = ["derive"] }
walkdir = "2.5.0"
csv = "1.3.1"
tempfile = "3.13.0"
indicatif = "0.17.10"
base64-simd = "0.8.0"
numpress-rs = "1.1.0"
identity-hash = "0.1.0"

tokio = { version = "1.47.1", optional = true }
object_store = { version = "0.12.4", optional = true, features = ["http"] }
futures = { version = "0.3.31", optional = true}
async_zip = { version = "0.0.18", features = ["tokio"], optional = true }
url = { version = "2.5.7", optional = true }
tokio-stream = "0.1.17"

[dev-dependencies]
clap = { version = "4.5.38", features = ["derive"] }
test-log = "0.2.12 "
tokio = { version = "1.47.1", features = ["rt-multi-thread"]}
serde_arrow = { version = "0.13.3", features = ["arrow-55"] }

[profile.release]
debug = true
